import type { MetadataRoute } from "next";

/**
 * Named crawlers that sometimes ignore `User-agent: *` and only honor a
 * block that lists their own token. Keep `*` as a separate rule as well.
 */
const NAMED_CRAWLERS = [
  "AddSearchBot",
  "AdIdxBot",
  "AdsBot-Google",
  "AdsBot-Google-Mobile",
  "AgentTimes",
  "AhrefsBot",
  "AI2Bot",
  "AI2Bot-DeepResearchEval",
  "Ai2Bot-Dolma",
  "aiHitBot",
  "AIWebIndex",
  "amazon-kendra",
  "amazon-QBusiness",
  "Amazonbot",
  "AmazonBuyForMe",
  "Amzn-SearchBot",
  "Amzn-User",
  "Andibot",
  "Anomura",
  "anthropic-ai",
  "APIs-Google",
  "ApifyBot",
  "ApifyWebsiteContentCrawler",
  "Applebot",
  "Applebot-Extended",
  "Aranet-SearchBot",
  "archive.org_bot",
  "atlassian-bot",
  "Awario",
  "AzureAI-SearchBot",
  "Baiduspider",
  "bedrockbot",
  "bigsur.ai",
  "bingbot",
  "BingPreview",
  "BLEXBot",
  "Bravebot",
  "Brightbot",
  "Brightbot 1.0",
  "BuddyBot",
  "Bytespider",
  "CCBot",
  "Channel3Bot",
  "ChatGLM-Spider",
  "ChatGPT Agent",
  "ChatGPT-User",
  "Claude-Code",
  "Claude-SearchBot",
  "Claude-User",
  "Claude-Web",
  "ClaudeBot",
  "Cloudflare-AutoRAG",
  "CloudVertexBot",
  "cohere-ai",
  "cohere-training-data-crawler",
  "Cotoyogi",
  "CragCrawler",
  "Crawl4AI",
  "Crawlspace",
  "Cursor",
  "DataForSeoBot",
  "Datenbank Crawler",
  "DeepSeekBot",
  "Devin",
  "Diffbot",
  "Diffbot-User",
  "Discordbot",
  "DotBot",
  "DoubaoBot",
  "DuckAssistBot",
  "DuckDuckBot",
  "Echobot Bot",
  "EchoboxBot",
  "ERNIEBot",
  "Exabot",
  "ExaBot",
  "ExaSearchBot",
  "FacebookBot",
  "facebookexternalhit",
  "Factset_spyderbot",
  "FeedFetcher-Google",
  "FirecrawlAgent",
  "FriendlyCrawler",
  "GeistHaus-PageFetcher",
  "Gemini-Deep-Research",
  "Google-Agent",
  "Google-CloudVertexBot",
  "Google-Extended",
  "Google-Firebase",
  "Google-Gemini-CLI",
  "Google-InspectionTool",
  "Google-NotebookLM",
  "GoogleAgent-Mariner",
  "GoogleAgent-URLContext",
  "Googlebot",
  "Googlebot-Image",
  "Googlebot-News",
  "Googlebot-Video",
  "GoogleOther",
  "GoogleOther-Image",
  "GoogleOther-Video",
  "GPTBot",
  "HenkBot",
  "ia_archiver",
  "iAskBot",
  "iaskspider",
  "iaskspider/2.0",
  "ICC-Crawler",
  "ImagesiftBot",
  "imageSpider",
  "img2dataset",
  "ISSCyberRiskCrawler",
  "kagi-fetcher",
  "Kangaroo Bot",
  "Kimi-SearchBot",
  "Kimi-User",
  "KimiBot",
  "KlaviyoAIBot",
  "KunatoCrawler",
  "laion-huggingface-processor",
  "LAIONDownloader",
  "LCC",
  "Lightpanda",
  "LinerBot",
  "LinkedInBot",
  "Linguee Bot",
  "LinkupBot",
  "Manus-User",
  "meta-externalagent",
  "Meta-ExternalAgent",
  "meta-externalfetcher",
  "Meta-ExternalFetcher",
  "meta-webindexer",
  "MistralAI-Index",
  "MistralAI-Training",
  "MistralAI-User",
  "MistralAI-User/1.0",
  "MJ12bot",
  "Mozilla-Tabstack",
  "msnbot",
  "MyCentralAIScraperBot",
  "NagetBot",
  "netEstate Imprint Crawler",
  "newsai",
  "NotebookLM",
  "NovaAct",
  "OAI-AdsBot",
  "OAI-SearchBot",
  "omgili",
  "omgilibot",
  "OpenAI",
  "opencode",
  "Operator",
  "PanguBot",
  "Panscient",
  "panscient.com",
  "Perplexity-User",
  "PerplexityBot",
  "PetalBot",
  "PhindBot",
  "Poggio-Citations",
  "Poseidon Research Crawler",
  "QualifiedBot",
  "Querit-SearchBot",
  "QueritBot",
  "QuillBot",
  "quillbot.com",
  "Qwantify",
  "QwenBot",
  "Reflectionbot",
  "SBIntuitionsBot",
  "Scrapy",
  "SemrushBot",
  "SemrushBot-OCOB",
  "SemrushBot-SWA",
  "SeznamBot",
  "Shap-User",
  "ShapBot",
  "Sidetrade indexer bot",
  "Slackbot",
  "Slackbot-LinkExpanding",
  "Slurp",
  "Sogou",
  "Storebot-Google",
  "TavilyBot",
  "Terra Cotta",
  "TerraCotta",
  "Thinkbot",
  "TikTokSpider",
  "Timpibot",
  "TongyiBot",
  "Trae",
  "TwinAgent",
  "Twitterbot",
  "UseAI",
  "VelenPublicWebCrawler",
  "WARDBot",
  "Webzio-Extended",
  "webzio-extended",
  "wpbot",
  "WRTNBot",
  "YaK",
  "YandexAdditional",
  "YandexAdditionalBot",
  "YandexBot",
  "YandexImages",
  "YiyanBot",
  "YouBot",
  "ZanistaBot",
];

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: "*",
        disallow: "/",
      },
      {
        userAgent: NAMED_CRAWLERS,
        disallow: "/",
      },
    ],
  };
}
